---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: scalerl
rules:
- apiGroups:
  - apps
  - ''
  resources:
  - 'deployments'
  verbs:
  - list
  - watch
  - status
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - create
  - watch
---
apiVersion: v1
kind: Namespace
metadata:
  name: scalerl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalerl
  namespace: scalerl
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scalerl
  namespace: scalerl
subjects:
- kind: ServiceAccount
  name: scalerl
  namespace: scalerl
roleRef:
  kind: ClusterRole
  name: scalerl
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalerl
  namespace: scalerl
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: scalerl
  replicas: 1
  template:
    metadata:
      labels:
        app: scalerl
    spec:
      serviceAccountName: scalerl
      imagePullSecrets:
      - name: regcred
      containers:
      - name: scalerl
        image: docker.pkg.github.com/philipcristiano/scalerl/scalerl:1578055579
        resources:
          requests:
            cpu: 75m
            memory: 512M
          limits:
            cpu: 1
            memory: 8Gi
        env:
        - name: HOME
          value: /app
