
---
apiVersion: v1
kind: Namespace
metadata:
  name: scalerl

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: scalerl
  namespace: scalerl
spec:
  selector:
    matchLabels:
      app: scalerl
  replicas: 1
  template:
    metadata:
      labels:
        app: scalerl
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: scalerl
        image: docker.pkg.github.com/philipcristiano/scalerl/scalerl:1574021602
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
