
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: scalerl
rules:
- apiGroups: ["watcher"]
  resources: ["deployments", "hpas"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["writer"]
  resources: ["hpas"]
  verbs: ["create"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: scalerl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalerl
  namespace: scalerl
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scalerl
  namespace: scalerl
subjects:
- kind: ServiceAccount
  name: scalerl
  namespace: scalerl
roleRef:
  kind: Role
  name: scalerl
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: scalerl
  namespace: scalerl
spec:
  selector:
    matchLabels:
      app: scalerl
  replicas: 1
  template:
    metadata:
      labels:
        app: scalerl
    spec:
      serviceAccountName: scalerl
      imagePullSecrets:
      - name: regcred
      containers:
      - name: scalerl
        image: docker.pkg.github.com/philipcristiano/scalerl/scalerl:1574166939
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 75m
